# DIAL-MPC
seed: 0
output_dir: flybody
n_steps: 400

env_name: Flybody
Nsample: 4096
Hsample: 32
Hnode: 8
Ndiffuse: 16
Ndiffuse_init: 32
temp_sample: 0.05
horizon_diffuse_factor: 0.9
traj_diffuse_factor: 0.5
update_method: mppi


robot_name: "fruitfly"
scene_name: "fruitfly_force_fast.xml"
sim_leg_control: torque
plot: false
record: false
real_time_factor: 1.0
sim_dt: 0.002
sync_mode: false


# Base environment
task_name: "fly"
randomize_tasks: False  # Whether to randomize the task.
# P gain, or a list of P gains for each joint.
kp: 100.0
# D gain, or a list of D gains for each joint.
kd: 10.0
debug: False
# dt of the environment step, not the underlying simulator step.
dt: 0.002
# timestep of the underlying simulator step. user is responsible for making sure it matches their model.
timestep: 0.002
backend: "mjx"  # backend of the environment.
# control method for the joints, either "torque" or "position"
leg_control: "torque"
action_scale: 1.0  # scale of the action space.
free_jnt: False
inference_mode: False
# Fly
free_jnt: True
end_eff_names:
  - claw_T1_left
  - claw_T1_right
  - claw_T2_left
  - claw_T2_right
  - claw_T3_left
  - claw_T3_right
appendage_names:
  - tarsus_T1_left
  - tarsus_T1_right
  - tarsus_T2_left
  - tarsus_T2_right
  - tarsus_T3_left
  - tarsus_T3_right
body_names:
  - thorax
  - head
  - rostrum
  - haustellum
  - labrum_left
  - labrum_right
  - antenna_left
  - antenna_right
  - wing_left
  - wing_right
  - abdomen
  - abdomen_2
  - abdomen_3
  - abdomen_4
  - abdomen_5
  - abdomen_6
  - abdomen_7
  - haltere_left
  - haltere_right
  - coxa_T1_left
  - femur_T1_left
  - tibia_T1_left
  - tarsus_T1_left
  - tarsus2_T1_left
  - tarsus3_T1_left
  - tarsus4_T1_left
  - claw_T1_left
  - coxa_T1_right
  - femur_T1_right
  - tibia_T1_right
  - tarsus_T1_right
  - tarsus2_T1_right
  - tarsus3_T1_right
  - tarsus4_T1_right
  - claw_T1_right
  - coxa_T2_left
  - femur_T2_left
  - tibia_T2_left
  - tarsus_T2_left
  - tarsus2_T2_left
  - tarsus3_T2_left
  - tarsus4_T2_left
  - claw_T2_left
  - coxa_T2_right
  - femur_T2_right
  - tibia_T2_right
  - tarsus_T2_right
  - tarsus2_T2_right
  - tarsus3_T2_right
  - tarsus4_T2_right
  - claw_T2_right
  - coxa_T3_left
  - femur_T3_left
  - tibia_T3_left
  - tarsus_T3_left
  - tarsus2_T3_left
  - tarsus3_T3_left
  - tarsus4_T3_left
  - claw_T3_left
  - coxa_T3_right
  - femur_T3_right
  - tibia_T3_right
  - tarsus_T3_right
  - tarsus2_T3_right
  - tarsus3_T3_right
  - tarsus4_T3_right
  - claw_T3_right
site_names: 
  - tracking[coxa_T1_left]
  - tracking[femur_T1_left]
  - tracking[tibia_T1_left]
  - tracking[tarsus_T1_left]
  - tracking[claw_T1_left]
  - tracking[coxa_T1_right]
  - tracking[femur_T1_right]
  - tracking[tibia_T1_right]
  - tracking[tarsus_T1_right]
  - tracking[claw_T1_right]
  - tracking[coxa_T2_left]
  - tracking[femur_T2_left]
  - tracking[tibia_T2_left]
  - tracking[tarsus_T2_left]
  - tracking[claw_T2_left]
  - tracking[coxa_T2_right]
  - tracking[femur_T2_right]
  - tracking[tibia_T2_right]
  - tracking[tarsus_T2_right]
  - tracking[claw_T2_right]
  - tracking[coxa_T3_left]
  - tracking[femur_T3_left]
  - tracking[tibia_T3_left]
  - tracking[tarsus_T3_left]
  - tracking[claw_T3_left]
  - tracking[coxa_T3_right]
  - tracking[femur_T3_right]
  - tracking[tibia_T3_right]
  - tracking[tarsus_T3_right]
  - tracking[claw_T3_right]
joint_names:
  - coxa_flexion_T1_left
  - coxa_twist_T1_left
  - femur_T1_left
  - femur_twist_T1_left
  - tibia_T1_left
  - tarsus_T1_left
  - coxa_flexion_T1_right
  - oxa_twist_T1_right
  - emur_T1_right
  - emur_twist_T1_right
  - tibia_T1_right
  - tarsus_T1_right
  - coxa_flexion_T2_left
  - coxa_twist_T2_left
  - femur_T2_left
  - femur_twist_T2_left
  - tibia_T2_left
  - tarsus_T2_left
  - coxa_flexion_T2_right
  - oxa_twist_T2_right
  - emur_T2_right
  - emur_twist_T2_right
  - tibia_T2_right
  - tarsus_T2_righ
  - coxa_flexion_T3_left
  - coxa_twist_T3_left
  - femur_T3_left
  - femur_twist_T3_left
  - tibia_T3_left
  - tarsus_T3_left
  - coxa_flexion_T3_right
  - oxa_twist_T3_right
  - emur_T3_right
  - emur_twist_T3_right
  - tibia_T3_right
  - tarsus_T3_rig
center_of_mass: thorax
# # Go2
# default_vx: 0.8
# default_vy: 0.0
# default_vyaw: 0.0
# ramp_up_time: 1.0
# gait: trot
